# Step-by-step demonstration of how to compile a C program using clang:

# 1. Create a file called hello.c with a basic Hello World program
$ clang hello.c -o hello

# 2. Run the executable generated by clang
$ ./hello

# 3. Compile a program with the cs50 library (if using the library)
$ clang -o hello hello.c -lcs50

# 4. Use make to simplify the compilation process
$ make hello